name: chat
description: "application"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  battery_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/fonts/
