name: sioren
description: "SiOren chat application"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.9.3
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  encrypt: ^5.0.3
  vibration: ^1.8.4
  audioplayers: ^6.0.0
  get: ^4.6.6
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/fonts/
